# Generated by Django 5.2.15 on 2026-07-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drawing",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Чертеж",
                "verbose_name_plural": "Чертежи",
            },
        ),
    ]
