# Generated by Django 5.2.15 on 2026-07-21 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название квалификации",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Например: WELD-01, TURN-01",
                        max_length=20,
                        unique=True,
                        verbose_name="Код квалификации",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Квалификация",
                "verbose_name_plural": "Квалификации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, verbose_name="Дата рождения"),
                ),
                (
                    "employee_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "work_area",
                    models.CharField(
                        help_text="Цех, участок, отдел",
                        max_length=100,
                        verbose_name="Участок",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("vacation", "В отпуске"),
                            ("sick", "Больничный"),
                            ("fired", "Уволен"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=16, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("hire_date", models.DateField(verbose_name="Дата приема на работу")),
                (
                    "fire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "qualification",
                    models.ManyToManyField(
                        related_name="employees",
                        to="employees.qualification",
                        verbose_name="Квалификации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name", "patronymic"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("plan", "Плановые часы"),
                            ("fact", "Фактические часы"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Часы"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("coment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления записи"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись рабочего времени",
                "verbose_name_plural": "Рабочее время",
                "ordering": ["date", "-created_at"],
                "unique_together": {("employee", "date", "entry_type")},
            },
        ),
    ]
